- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
  - name: DURATION
    prompt: Please enter the duration
  - name: TRAINER
    prompt: Please enter the trainer name

  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: 'Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, and Trainer is {{TRAINER}}'