- name: create user
  hosts: web
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_error: True

  - name: print the user information
    ansible.builtin.debug:
     msg: "user info {{USER}}"