- name: loops demo
  hosts: localhost
  connection: local
  tasks:
  - name: print names
    ansible.builtin.package:
     name: {{ item}}
     state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd
  